### ISSUE TITLE
Release / Build

### ISSUE THREAD

**Issue by pixelroll** [6xingyv/Jellyflix#31]
Hi, I'm very interested in your project, will there be a release soon? 

I tried to build via source code but under windows it seems impossible.

Thank you and good continuation.

**Comment by 6xingyv** [comment]
Sorry for the late update! This app is still in a very early stage and not prepared for its release! And recently, I reset my computer by mistake and lost my local codebase...... And after a deep learning in Compose, I think the structure of my project is a MESS! So I decide to rewrite it again in next weeks! Thanks for waiting, sorry for another wait😔

**Comment by pixelroll** [comment]
> Sorry for the late update! This app is still in a very early stage and not prepared for its release! And recently, I reset my computer by mistake and lost my local codebase...... And after a deep learning in Compose, I think the structure of my project is a MESS! So I decide to rewrite it again in next weeks! Thanks for waiting, sorry for another wait😔

I'll wait as long as it takes
